//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CenterBookingEntities : DbContext
    {
        public CenterBookingEntities()
            : base("name=CenterBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<Assignment2.Models.Booking> Bookings { get; set; }

        public System.Data.Entity.DbSet<Assignment2.Models.Center> Centers { get; set; }
    }
}
